on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: Update CONTRIBUTORS.md
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@master
              with:
                  readme_path: "CONTRIBUTORS.md"
                  user_username: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
